/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'projeto' at '06/10/16 15:50' with Gradle 2.13
 *
 * @author projeto, @date 06/10/16 15:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
